name: gnome-dictionary
adopt-info: gnome-dictionary
summary: Check word definitions and spellings in an online dictionary
description: |
  GNOME Dictionary is a simple dictionary application that looks up
  definitions of words online.

  Though it looks up English definitions by default, you can easily switch to
  Spanish or add other online dictionaries using the DICT protocol to suit your
  needs.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core22

slots:
  # for GtkApplication registration
  gnome-dictionary:
    interface: dbus
    bus: session
    name: org.gnome.Dictionary

apps:
  gnome-dictionary:
    command: usr/bin/gnome-dictionary
    extensions: [gnome]
    plugs:
      - network
    desktop: usr/share/applications/org.gnome.Dictionary.desktop

parts:
  meson-deps:
    plugin: nil
    source: https://github.com/mesonbuild/meson.git
    source-tag: '0.62.2'
    override-build: |
      pip install .
    build-packages:
      - python3-pip
      - ninja-build

  gnome-dictionary:
    source: https://gitlab.gnome.org/GNOME/gnome-dictionary.git
    source-type: git
    after: [ meson-deps ]
    source-tag: '40.0'
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags --abbrev=10)
      # Remove the meson.build line for erroring on redundant-declarations
      sed -i.bak -e '/.*-Werror=redundant-decls.*$/d' src/meson.build
      patch -p1 < $SNAPCRAFT_PROJECT_DIR/patches/01-fix_build.diff
    override-build: |
      sed -i.bak -e 's|Icon=@application_id@$|Icon=${SNAP}/meta/gui/org.gnome.Dictionary.svg|g' $SNAPCRAFT_PART_SRC/data/org.gnome.Dictionary.desktop.in.in
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp $SNAPCRAFT_PART_SRC/data/icons/scalable/org.gnome.Dictionary.svg $SNAPCRAFT_PART_INSTALL/meta/gui/
      snapcraftctl build
